### ISSUE TITLE
iOS badge notifications don’t disappear after viewing posts 

### ISSUE THREAD

**Issue by ChronicleFlask** [bluesky-social/social-app#1090]
**Describe the bug**

The iOS badge counter doesn’t reset to zero (disappear) after viewing notifications: it only disappears after at least one post/reply/follow has been actively tapped. 

**To Reproduce**

1. Do or post something that other users find engaging/encourages them to follow you 
2. Note badge counter on iOS device
3. Open Bluesky app, tap on bell icon for notifications, but DON’T interact further with notifications 
4. Close Bluesky app
5. Note that iOS badge counter is unchanged (even though you’ve “seen” the notifications)

**Expected behavior**

Badge counter resets to zero after opening the app and simply viewing notification list.

**Details**

 - Platform: iOS 
 - Platform version: 16.6
 - App version: 1.42

**Comment by pfrazee** [comment]
Handing to @ansh 💪

**Comment by stefanmve** [comment]
This also happens in my browser as well.

**Comment by ansh** [comment]
Should be fixed with #1095

**Comment by mschwendener** [comment]
Same in Chrome on desktop (supposing the fix is not live yet).

Also: When I click on the notification in the left column, this should automatically show me the new notifications, without an additional click.

**Comment by ansh** [comment]
Should be fixed @ChronicleFlask 

@stefanmve The issue you are mentioning is different. Since this issue talks about the _native_ iOS badge. Please open a new issue if you are still facing the problem on browser/web.

**Comment by ChronicleFlask** [comment]
I’ve just installed the latest iOS version (1.48 on iOS 16.6) and it isn’t fixed – the behaviour remains the same.

**Comment by ChronicleFlask** [comment]
This isn’t fixed on iOS. The behaviour remains the same with the latest update.

**Comment by pfrazee** [comment]
Reopening because we're reverting the change that was made for this
