### ISSUE TITLE
Crash opening image crop on Android

### ISSUE THREAD

**Issue by LooneyH** [bluesky-social/social-app#9288]
### Steps to Reproduce

1. Open Bluesky.
2. Attach image to post.
3. Tap the button to crop the image.
4. Bluesky crashes.

### What platform(s) does this occur on?

Android

### Device Info

Google Pixel 7, Android 16

### What version of the app are you using?

Build version: 1.109.0.727; Bundle info: 2a72238 (prod); Bundle date: 25102719; Platform: android; Platform version: 36; 

### Additional Information

This was not an issue until this most recent update. The cropping tool feels like it needs a bit of refinement anyway as it currently falls behind UI elements if it's a tall aspect ratio and a bit clunky, but as it stands here it's not functional at all.

**Comment by LooneyH** [comment]
I've just tested this now again on the newest release 1.110 and the image crop still is crashing on Android, worth having a further look

**Comment by mozzius** [comment]
Damn ok, there was _a_ crash fixed in the update but it must be a different one

**Comment by LooneyH** [comment]
I'm not sure if there's a debugging mode in the app that I can provide some more detail on crash logs or something, I can test some fixes if you can't seem to replicate it with a build in github actions if need be, too

**Comment by mozzius** [comment]
Could you provide an example of an image that is causing trouble? Is it a weird format or something?

**Comment by LooneyH** [comment]
It's literally any image I try. I've tried HDR photos using a P3 colour space, SDR photos, screenshots, images saved _from_ Bluesky itself, everything just makes it crash. It's only the cropping tool itself as the media does upload and alt text works fine on both photos and videos.

**Comment by LooneyH** [comment]
Just confirming the crash is still present, and is across multiple accounts, too. Is there anything you want me to do to help troubleshoot?

**Comment by LooneyH** [comment]
Thought I'd just update that the issue is still present as of 1.115, did notice it in 1.114 too but didn't wanna just post an update on every release lol
